[package]
name = "johnnyd-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
